config/routes.rb
Rails.application.routes.draw do
  get 'help', to: 'help#index'

  resources :paydays
  resources :bills

  get 'calendar/index'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'home#index'

  post '/calendar_settings', to: 'calendar#settings'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  before_action :set_calendar_events, only: :index
  before_action :set_target_account_balance, only: :index
  # before_action :set_next_deposit, only: :index
  # before_action :set_last_deposit, only: :index

  def index; end

  def set_next_deposit
    next_payday = Payday.where(user_id: current_user.id).all.flat_map(&:next_payday)
    next_payday = next_payday.any? ? next_payday.min_by(&:date) : nil # Check for [nil] returned
    @next_deposit = nil if next_payday.nil? || balance_at(next_payday.date) - @target_account_balance
  end

  def set_last_deposit
    last_payday = Payday.where(user_id: current_user.id).all.flat_map(&:previous_payday)
    last_payday = last_payday.any? ? last_payday.max_by(&:date) : nil # Check for [nil] returned
    @last_deposit = nil if last_payday.nil? || @target_account_balance - (balance_at(last_payday.date - 1.day))
  end

  def set_target_account_balance
    date = params[:date] || Date.today
    date = date.to_date + 1.second
    @target_account_balance = account_balance_at(date)
    # @target_account_balance = payday_balance(date)
  end

  def set_calendar_events
    @bills = Bill.where(user_id: current_user.id).all
    @calendar_bills = @bills.flat_map { |x| x.calendar_bills(params.fetch(:start_date, Time.zone.now)) }
    @paydays = Payday.where(user_id: current_user.id).all
    @calendar_paydays = @paydays.flat_map { |x| x.calendar_paydays(params.fetch(:start_date, Time.zone.now)) }
    @calendar_account_balances = cookies[:show_balance_each_day] ? calendar_account_balances(params.fetch(:start_date, Time.zone.now)) : []
    @calendar_payday_deposits = cookies[:show_payday_deposits] ? calendar_payday_deposits(params.fetch(:start_date, Time.zone.now)) : []
    @events = @calendar_account_balances + @calendar_payday_deposits + @calendar_bills + @calendar_paydays
  end

  def account_balance_at(date = Date.today)
    last_payday = Payday.where(user_id: current_user.id).all.flat_map { |x| x.previous_payday(date) }
    last_payday = last_payday.any? ? last_payday.max_by(&:date) : nil # Check for [nil] returned

    bills_since_last_payday = Bill.where(user_id: current_user.id).all.flat_map do |x|
      x.bills_between(last_payday.date, date)
    end

    # TODO: Figure out what to do when there is not a previous payday
    last_payday ? payday_balance(last_payday.date) - bills_since_last_payday.inject(0) { |sum, x| sum + x.amount } : -1
    # last_payday ? payday_deposit(last_payday.date) : -1
  end

  def payday_balance(date)
    paydays = Payday.where(user_id: current_user.id).all
    upcoming_bills = Bill.where(user_id: current_user.id).all.flat_map do |x|
      x.next_bill(date)
    end
    balance = 0
    upcoming_bills.each do |bill|
      paydays_bill_cycle = paydays.flat_map { |x| x.paydays_between(bill.previous_bill(bill.date).date, bill.date) }
      num_paydays_bill_cycle = paydays_bill_cycle.length
      num_paydays_past = paydays_bill_cycle.select { |x| x.date <= date }.length
      balance += num_paydays_past * (bill.amount / num_paydays_bill_cycle)
      puts "DEBUG: #{bill.name} = #{bill.previous_bill(bill.date).date} - #{bill.date}"
      puts "DEBUG: #{bill.name} = #{num_paydays_past} * (#{bill.amount} / #{num_paydays_bill_cycle})"
    end
    balance
  end

  def payday_deposit(date)
    paydays = Payday.where(user_id: current_user.id).all
    upcoming_bills = Bill.where(user_id: current_user.id).all.flat_map do |x|
      x.next_bill(date)
    end
    balance = 0
    upcoming_bills.each do |bill|
      paydays_bill_cycle = paydays.flat_map { |x| x.paydays_between(bill.previous_bill(bill.date).date, bill.date) }
      num_paydays_bill_cycle = paydays_bill_cycle.length
      balance += bill.amount / num_paydays_bill_cycle
      # puts "DEBUG: #{bill.name} = #{bill.previous_bill(bill.date).date} - #{bill.date}"
      # puts "DEBUG: #{bill.name} = #{bill.amount} / #{num_paydays_bill_cycle}"
    end
    balance
  end

  def calendar_account_balances(start)
    start_date = start.to_time.beginning_of_month.beginning_of_week
    end_date = start.to_time.end_of_month.end_of_week

    start_date.to_date.upto(end_date.to_date).map do |x|
      x += 1.second
      AccountBalance.new(x, account_balance_at(x))
    end
  end

  def calendar_payday_deposits(start)
    start_date = start.to_time.beginning_of_month.beginning_of_week
    end_date = start.to_time.end_of_month.end_of_week

    paydays = Payday.where(user_id:  current_user.id).all
    payday_dates = paydays.flat_map { |x| x.paydays_between(start_date, end_date) }
    payday_dates.map { |x| PaydayDeposit.new(x.date, payday_deposit(x.date)) }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="mx-3 mt-3">
  <% if @bills.empty? && @paydays.empty? %>
    <div class="alert alert-warning">Add some bills and paydays to get started.</div>
  <% elsif @bills.empty? && !@paydays.empty? %>
    <div class="alert alert-warning">Add some bills to get started.</div>
  <% elsif !@bills.empty? && @paydays.empty? %>
    <div class="alert alert-warning">Add some paydays to get started.</div>
  <% elsif !@bills.empty? && !@paydays.empty? %>
    <div class="row">
      <div class="col-xl-8">
        <%= month_calendar events: @events do |date, events| %>
          <%= date.day %>

          <% events.each do |event| %>
            <% if event.is_a? AccountBalance %>
              <br>
              <span class="badge bg-light text-dark">$<%= "%.2f" % event.amount %></span>
            <% elsif event.is_a? PaydayDeposit %>
              <br>
              <span class="badge bg-primary">$<%= "%.2f" % event.amount %></span>
            <% elsif event.is_a? Bill %>
              <br>
              <%= link_to bill_path(event.id) do %>
                <span class="badge bg-danger"><%= event.name %> - $<%= "%.2f" % event.amount %></span>
              <% end %>
            <% elsif event.is_a? Payday %>
              <br>
              <%= link_to payday_path(event.id) do %>
                <span class="badge bg-success">Payday - <%= event.name %></span>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
        <!-- Form is submitted on change of switch -->
        <%= form_with url: '/calendar_settings', id: 'calendar_settings', local: false do |form| %>
          <div class="form-check form-switch mb-3">
            <input class="form-check-input" type="checkbox" id="show_balance_each_day" name="show_balance_each_day"
                   <% if cookies[:show_balance_each_day] %>checked
                   <% end %>>
            <label class="form-check-label" for="show_balance_each_day">Show account balance for each day?</label>
          </div>
          <div class="form-check form-switch mb-3">
            <input class="form-check-input" type="checkbox" id="show_payday_deposits" name="show_payday_deposits"
                   <% if cookies[:show_payday_deposits] %>checked
                   <% end %>>
            <label class="form-check-label" for="show_balance_each_day">Show deposit amount for each payday?</label>
          </div>
        <% end %>
      </div>

      <div class="col-xl-4">
        <h1>There should be <span class="badge bg-secondary">$<%= "%.2f" % @target_account_balance %></span> in your
          bills account
          <% if params.dig(:date) %> on <%= params[:date] %>
          <% end %></h1>
        <!--      <h1>You will deposit <span class="badge bg-secondary">$<%#= "%.2f" % @next_deposit %></span> at your next payday on-->
        <!--        Xxxday the Xth</h1>-->
        <!--      <h1>You should have deposited <span class="badge bg-secondary">$<%#= "%.2f" % @last_deposit %></span> at your last-->
        <!--        payday on Xxxday the Xth</h1>-->
      </div>
    </div>

  <% end %>
</div>

<%= javascript_pack_tag 'calendar', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'home', 'data-turbolinks-track': 'reload' %>