config/routes.rb
Rails.application.routes.draw do
  get 'help', to: 'help#index'

  resources :paydays
  resources :bills

  get 'calendar/index'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'home#index'

  post '/calendar_settings', to: 'calendar#settings'
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user

  # Parse the IceCube rule for a Bill
  def schedule
    return unless recurring

    IceCube::Schedule.from_yaml recurring # Parse rule from yaml in DB
  end

  # Returns the next occurrence or recurrence of a Bill
  def next_bill(start = Date.today)
    if recurring.nil?
      date > Date.today ? [self] : nil
    else
      x = schedule.next_occurrence(start.to_time) # Get occurrence
      Bill.new(id: id, name: name, amount: amount, date: x, recurring: recurring) # Create new in memory bill
    end
  end

  # Returns the previous occurrence or recurrence of a Bill
  def previous_bill(start = Date.today)
    if recurring.nil?
      date < Date.today ? [self] : nil
    else
      puts start.to_time + 1.hour
      x = schedule.previous_occurrence(start.to_time - 1.hour) # Get occurrence
      Bill.new(id: id, name: name, amount: amount, date: x) # Create new in memory bill
    end
  end

  # Returns a Bill and all its recurrences that lie in a given time period
  def bills_between(start_date, end_date)
    if recurring.nil?
      date > Date.today && date < end_date ? [self] : nil
    else
      schedule.occurrences_between(start_date.to_time + 1.hour, end_date.to_time, spans: true).map do |x| # Get occurrences
        Bill.new(id: id, name: name, amount: amount, date: x) # Create new in memory bill
      end
    end
  end

  # Return occurrences and recurrences of a Bill for the calendar display month
  def calendar_bills(start)
    if recurring.nil?
      [self] # Return the original bill if recurring is nil
    else
      start_date = start.to_time.beginning_of_month.beginning_of_week
      end_date = start.to_time.end_of_month.end_of_week

      schedule.occurrences_between(start_date, end_date).map do |x| # Get occurrences
        Bill.new(id: id, name: name, amount: amount, date: x) # Create new in memory bill
      end
    end
  end

  # Map date to start_time for simple_calendar
  def start_time
    date
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bill, only: %i[show edit update destroy]

  # GET /bills or /bills.json
  def index
    @bills = Bill.where(user_id: current_user.id).all
  end

  # GET /bills/1 or /bills/1.json
  def show; end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
    return unless @bill.recurring

    hash = @bill.schedule.to_hash
    @rule_type = hash[:rrules][0][:rule_type].delete_prefix('IceCube::').delete_suffix('Rule').downcase
    @rule_interval = hash[:rrules][0][:interval]
    @occurs_until = hash[:end_time]&.to_date
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(name: params[:bill][:name], amount: params[:bill][:amount], date: params[:bill][:date])
    @bill.user_id = current_user.id
    @bill.recurring = generate_recurring_yaml

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: "Bill was successfully created." }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(name: params[:bill][:name], amount: params[:bill][:amount], date: params[:bill][:date], recurring: generate_recurring_yaml)
        format.html { redirect_to @bill, notice: "Bill was successfully updated." }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bill
    @bill = Bill.where(user_id: current_user.id).find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def bill_params
    params.require(:bill).permit(:name, :amount, :date, :recurring, :recurring_bool, :recurring_every, :recurring_period, :occurs_until)
  end

  def generate_recurring_yaml
    return unless params[:bill][:recurring_bool] == '1'

    schedule = if params[:bill][:occurs_until].empty? then
                 IceCube::Schedule.new(Date.parse(params[:bill][:date]))
               else
                 IceCube::Schedule.new(Date.parse(params[:bill][:date]), end_time: Date.parse(params[:bill][:occurs_until]))
               end

    case params[:bill][:recurring_period]
    when 'daily'
      schedule.add_recurrence_rule IceCube::Rule.daily(params[:bill][:recurring_every])
    when 'weekly'
      schedule.add_recurrence_rule IceCube::Rule.weekly(params[:bill][:recurring_every])
    when 'monthly'
      schedule.add_recurrence_rule IceCube::Rule.monthly(params[:bill][:recurring_every])
    when 'yearly'
      schedule.add_recurrence_rule IceCube::Rule.yearly(params[:bill][:recurring_every])
    end

    schedule.to_yaml
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= form_with model: bill, html: { class: 'mb-3' } do |form| %>
  <% if bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
        <% bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="input-group mb-3">
    <span class="input-group-text">$</span>
    <%= form.number_field :amount, class: 'form-control', required: true, step: '.01' %>
  </div>

  <div class="mb-3">
    <%= form.label :date, class: 'form-label' %>
    <%= form.date_field :date, class: 'form-control', required: true %>
  </div>

  <div class="form-check form-switch mb-3">
    <%= form.check_box 'recurring_bool', class: 'form-check-input', id: 'recurringCheck',
                       checked: @bill.recurring ? true : false %>
    <%= form.label 'Recurring?', class: 'form-check-label' %>
  </div>

  <div id="recurring" <% unless @bill.recurring %>class="visually-hidden"<% end %>>
    <div class="d-flex justify-content-start mb-3">
      <span class="align-self-center flex-shrink-0 me-2">Recurring every</span>
      <%= form.number_field 'recurring_every', class: 'form-control me-2', value: @rule_interval,
                            required: @bill.recurring ? true : false %>
      <%= form.select 'recurring_period',
                      options_for_select(
                        [%w[Day(s) daily], %w[Week(s) weekly], %w[Month(s) monthly], %w[Year(s) yearly]], @rule_type),
                      {}, { class: 'form-select' } %>
    </div>

    <div class="d-flex justify-content-start mb-1">
      <span class="align-self-center flex-shrink-0 me-2">Occurs until</span>
      <%= form.date_field 'occurs_until', class: 'form-control', value: @occurs_until %>
    </div>
    <div id="emailHelp" class="form-text mb-3">Leave this field blank for an indefinitely repeating event.</div>
  </div>

  <%= form.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/bills/edit.html.erb
<div style="max-width: 450px" class="mx-auto px-3 mt-3">
  <h1>Editing Bill</h1>

  <%= render 'form', bill: @bill %>

  <%= link_to 'Show', @bill %> |
  <%= link_to 'Back', bills_path %>
</div>

<%= javascript_pack_tag 'bill', 'data-turbolinks-track': 'reload' %>

app/views/bills/index.html.erb
<div class="px-3 mt-3">
  <h1>Bills</h1>

  <div class="table-responsive">
    <table class="table">
      <thead class="table-light">
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Amount</th>
        <th scope="col">Date</th>
        <th scope="col">Recurring</th>
        <th scope="col"></th>
      </tr>
      </thead>

      <tbody>
      <% @bills.each do |bill| %>
        <tr>
          <td><%= bill.name %></td>
          <td>$<%= "%.2f" % bill.amount %></td>
          <td><%= bill.date %></td>
          <% if bill.recurring %>
            <td><%= bill.schedule.to_s %></td>
          <% else %>
            <td></td>
          <% end %>
          <td style="text-align: end"><%= link_to 'Show', bill %> <%= link_to 'Edit', edit_bill_path(bill) %> <%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

  <%= link_to 'New Bill', new_bill_path, class: 'btn btn-primary' %>
</div>

app/views/bills/new.html.erb
<div style="max-width: 450px" class="mx-auto px-3 mt-3">
  <h1>New Bill</h1>

  <%= render 'form', bill: @bill %>

  <%= link_to 'Back', bills_path %>
</div>

<%= javascript_pack_tag 'bill', 'data-turbolinks-track': 'reload' %>

app/views/bills/show.html.erb
<div style="max-width: 450px" class="mx-auto px-3 mt-3">
  <p>
    <strong>Name:</strong>
    <%= @bill.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= @bill.amount %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @bill.date %>
  </p>

  <p>
    <strong>Recurring:</strong>
    <%= @bill.schedule.to_s %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @bill.user_id %>
  </p>

  <%= link_to 'Edit', edit_bill_path(@bill) %> |
  <%= link_to 'Back', bills_path %>
</div>