config/routes.rb
Rails.application.routes.draw do
  get 'help', to: 'help#index'

  resources :paydays
  resources :bills

  get 'calendar/index'

  devise_for :users, controllers: { registrations: 'registrations' }

  root 'home#index'

  post '/calendar_settings', to: 'calendar#settings'
end

app/models/payday.rb
class Payday < ApplicationRecord
  belongs_to :user

  # Parse the IceCube rule for a Payday
  def schedule
    return unless recurring

    IceCube::Schedule.from_yaml recurring # Parse rule from yaml in DB
  end

  # Returns the next future occurrence or recurrence of a Payday
  def calendar_paydays(start)
    if recurring.nil?
      [self] # Return the original payday if recurring is nil
    else
      start_date = start.to_time.beginning_of_month.beginning_of_week
      end_date = start.to_time.end_of_month.end_of_week

      schedule.occurrences_between(start_date, end_date).map do |x| # Get occurrences
        Payday.new(id: id, name: name, date: x) # Create new in memory payday
      end
    end
  end

  # Returns the next occurrence or recurrence of a Payday
  def next_payday(date = Date.today)
    if recurring.nil?
      date > Date.today ? [self] : nil
    else
      x = schedule.next_occurrence(date.to_time) # Get occurrences
      return nil if x.nil?

      Payday.new(id: id, name: name, date: x) # Create new in memory payday
    end
  end

  # Returns the previous occurrence or recurrence of a Payday
  def previous_payday(date = Date.today)
    if recurring.nil?
      date < Date.today ? [self] : nil
    else
      x = schedule.previous_occurrence(date.to_time) # Get occurrences
      return nil if x.nil?

      Payday.new(id: id, name: name, date: x) # Create new in memory payday
    end
  end

  # Returns a Payday and all its recurrences that lie in a given time period
  def paydays_between(start_date, end_date)
    if recurring.nil?
      date > Date.today && date < end_date ? [self] : nil
    else
      schedule.occurrences_between(start_date.to_time, end_date.to_time, spans: true).map do |x| # Get occurrences
        Payday.new(id: id, name: name, date: x) # Create new in memory payday
      end
    end
  end

  # Map date to start_time for simple_calendar
  def start_time
    date
  end
end

app/controllers/paydays_controller.rb
class PaydaysController < ApplicationController
  before_action :set_payday, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /paydays or /paydays.json
  def index
    @paydays = Payday.where(user_id: current_user.id).all
  end

  # GET /paydays/1 or /paydays/1.json
  def show
  end

  # GET /paydays/new
  def new
    @payday = Payday.new
  end

  # GET /paydays/1/edit
  def edit
    return unless @payday.recurring

    hash = @payday.schedule.to_hash
    @rule_type = hash[:rrules][0][:rule_type].delete_prefix('IceCube::').delete_suffix('Rule').downcase
    @rule_interval = hash[:rrules][0][:interval]
    @occurs_until = hash[:end_time]&.to_date
  end

  # POST /paydays or /paydays.json
  def create
    @payday = Payday.new(name: params[:payday][:name], date: params[:payday][:date], recurring: generate_recurring_yaml,
                         user_id: current_user.id)

    respond_to do |format|
      if @payday.save
        format.html { redirect_to @payday, notice: "Payday was successfully created." }
        format.json { render :show, status: :created, location: @payday }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paydays/1 or /paydays/1.json
  def update
    respond_to do |format|
      if @payday.update(name: params[:payday][:name], date: params[:payday][:date], recurring: generate_recurring_yaml)
        format.html { redirect_to @payday, notice: "Payday was successfully updated." }
        format.json { render :show, status: :ok, location: @payday }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paydays/1 or /paydays/1.json
  def destroy
    @payday.destroy
    respond_to do |format|
      format.html { redirect_to paydays_url, notice: "Payday was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payday
    @payday = Payday.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payday_params
    params.require(:payday).permit(:name, :date, :recurring)
  end

  def generate_recurring_yaml
    return unless params[:payday][:recurring_bool] == '1'

    schedule = if params[:payday][:occurs_until].empty? then
                 IceCube::Schedule.new(Date.parse(params[:payday][:date]))
               else
                 IceCube::Schedule.new(Date.parse(params[:payday][:date]), end_time: Date.parse(params[:payday][:occurs_until]))
               end

    case params[:payday][:recurring_period]
    when 'daily'
      schedule.add_recurrence_rule IceCube::Rule.daily(params[:payday][:recurring_every])
    when 'weekly'
      schedule.add_recurrence_rule IceCube::Rule.weekly(params[:payday][:recurring_every])
    when 'monthly'
      schedule.add_recurrence_rule IceCube::Rule.monthly(params[:payday][:recurring_every])
    when 'yearly'
      schedule.add_recurrence_rule IceCube::Rule.yearly(params[:payday][:recurring_every])
    end

    schedule.to_yaml
  end
end

app/helpers/paydays_helper.rb
module PaydaysHelper
end

app/views/paydays/_form.html.erb
<%= form_with(model: payday) do |form| %>
  <% if payday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payday.errors.count, "error") %> prohibited this payday from being saved:</h2>

      <ul>
        <% payday.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :date, class: 'form-label' %>
    <%= form.date_field :date, class: 'form-control', required: true %>
  </div>

  <div class="form-check form-switch mb-3">
    <%= form.check_box 'recurring_bool', class: 'form-check-input', id: 'recurringCheck',
                       checked: @payday.recurring ? true : false %>
    <%= form.label 'Recurring?', class: 'form-check-label' %>
  </div>

  <div id="recurring"
       <% unless @payday.recurring %>class="visually-hidden"
  <% end %>>
    <div class="d-flex justify-content-start mb-3">
      <span class="align-self-center flex-shrink-0 me-2">Recurring every</span>
      <%= form.number_field 'recurring_every', class: 'form-control me-2', value: @rule_interval,
                            required: @payday.recurring ? true : false %>
      <%= form.select 'recurring_period',
                      options_for_select(
                        [%w[Day(s) daily], %w[Week(s) weekly], %w[Month(s) monthly], %w[Year(s) yearly]], @rule_type),
                      {}, { class: 'form-select' } %>
    </div>

    <div class="d-flex justify-content-start mb-1">
      <span class="align-self-center flex-shrink-0 me-2">Occurs until</span>
      <%= form.date_field 'occurs_until', class: 'form-control', value: @occurs_until %>
    </div>
    <div id="emailHelp" class="form-text mb-3">Leave this field blank for an indefinitely repeating event.</div>
  </div>

  <%= form.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/paydays/edit.html.erb
<div style="max-width: 450px" class="mx-auto px-3 mt-3">
  <h1>Editing Payday</h1>

  <%= render 'form', payday: @payday %>

  <%= link_to 'Show', @payday %> |
  <%= link_to 'Back', paydays_path %>
</div>

<%= javascript_pack_tag 'payday', 'data-turbolinks-track': 'reload' %>

app/views/paydays/index.html.erb
<div class="px-3 mt-3">
  <h1>Paydays</h1>

  <table class="table">
    <thead class="table-light">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Date</th>
      <th scope="col">Recurring</th>
      <th scope="col"></th>
    </tr>
    </thead>

    <tbody>
    <% @paydays.each do |payday| %>
      <tr>
        <td><%= payday.name %></td>
        <td><%= payday.date %></td>
        <% if payday.recurring %>
          <td><%= payday.schedule.to_s %></td>
        <% else %>
          <td></td>
        <% end %>
        <td style="text-align: end"><%= link_to 'Show', payday %> <%= link_to 'Edit', edit_payday_path(payday) %> <%= link_to 'Destroy', payday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'New Payday', new_payday_path, class: 'btn btn-primary' %>
</div>

app/views/paydays/new.html.erb
<div style="max-width: 450px" class="mx-auto px-3 mt-3">
  <h1>New Payday</h1>

  <%= render 'form', payday: @payday %>

  <%= link_to 'Back', paydays_path %>
</div>

<%= javascript_pack_tag 'payday', 'data-turbolinks-track': 'reload' %>

app/views/paydays/show.html.erb
<div style="max-width: 450px" class="mx-auto px-3 mt-3">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @payday.name %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @payday.date %>
  </p>

  <p>
    <strong>Recurring:</strong>
    <%= @payday.schedule.to_s %>
  </p>

  <%= link_to 'Edit', edit_payday_path(@payday) %> |
  <%= link_to 'Back', paydays_path %>
</div>